name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Python ve Java Hazirla
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Java Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Sistem Paketlerini Kur
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential libltdl-dev python3-pip lld
          pip install --upgrade pip
          pip install "cython<3.0.0" wheel setuptools
          pip install --user --upgrade buildozer

      - name: APK Hazirla (Buildozer)
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug

      # İŞTE EKSİK OLAN KRİTİK ADIM BURASI:
      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4
        with:
          name: maas-takip-app-dosyasi
          path: bin/*.apk
