name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04 # Sürümü sabitledik ki sürpriz yaşatmasın
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Sistem Paketlerini Kur
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev \
          build-essential libltdl-dev python3-pip lld
          pip install --upgrade pip
          pip install wheel setuptools "cython<3.0.0" buildozer
      - name: APK Hazirla
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Önbelleği temizle ve build başlat
          rm -rf .buildozer
          yes | buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: maas-takip-apk
          path: bin/*.apk
